# Generated by Django 3.2.5 on 2021-07-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='club_card',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='confirmed_email',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='region',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='legalaccount',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.account'),
            preserve_default=False,
        ),
    ]
