# Generated by Django 3.2.4 on 2021-07-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210708_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='confirmed_email',
        ),
        migrations.RemoveField(
            model_name='legalaccount',
            name='confirmed_email',
        ),
    ]
