# Generated by Django 3.2.5 on 2021-07-02 08:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('album', models.ImageField(blank=True, upload_to='images')),
                ('uploads', models.FileField(blank=True, upload_to='uploads')),
                ('link', models.URLField(max_length=256)),
                ('slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=256)),
                ('meta_keyword', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
