# Generated by Django 3.2.5 on 2021-07-02 08:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_image', models.ImageField(blank=True, upload_to='images')),
                ('description', ckeditor.fields.RichTextField()),
                ('inner_number', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('old_price', models.IntegerField()),
                ('promo_price', models.IntegerField()),
                ('in_stock', models.IntegerField()),
                ('uploads', models.FileField(blank=True, upload_to='uploads')),
                ('is_new_product', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=256)),
                ('meta_keyword', models.CharField(max_length=50)),
                ('meta_title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('bought_together', models.ManyToManyField(blank=True, related_name='_products_product_bought_together_+', to='products.Product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_active_buy', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromotionPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('main_image', models.ImageField(blank=True, upload_to='images')),
                ('unit', models.IntegerField()),
                ('you_save', models.CharField(max_length=50)),
                ('upload', models.FileField(blank=True, upload_to='uploads')),
                ('is_new', models.BooleanField()),
                ('weight', models.IntegerField()),
                ('compare', models.BooleanField()),
                ('slug', models.SlugField()),
                ('meta_description', models.CharField(max_length=256)),
                ('meta_keyword', models.CharField(max_length=50)),
                ('meta_title', models.CharField(max_length=50)),
                ('is_acitve', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
                ('products', models.ManyToManyField(to='products.Product')),
                ('related_products', models.ManyToManyField(blank=True, related_name='_products_promotionpacket_related_products_+', to='products.PromotionPacket')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_page.video')),
            ],
            options={
                'verbose_name': 'Promotion Packet',
                'verbose_name_plural': 'Promotion Packets',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'ProductCharacteristic',
                'verbose_name_plural': 'ProductCharacteristics',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='_products_product_related_products_+', to='products.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='video_page.video'),
        ),
    ]
